spring:
  application:
    name: agentic-ai
  r2dbc:
    username: postgres
    url: r2dbc:postgresql://localhost:5432/booking
  data:
    redis:
      host: localhost
      port: 6379
      password: test
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      model-name: gpt-4o
      log-requests: true
      log-responses: true
logging.level:
          web: DEBUG
          redis: DEBUG
server:
  port: 8081
cache:
  parking-slot:
    prefix: parking-slot
  booking-slot:
    prefix: booking-slot

