spring:
  application:
    name: agentic-ai
  r2dbc:
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      model-name: gpt-4o
      log-requests: true
      log-responses: true
logging.level:
          web: DEBUG
          redis: DEBUG
server:
  port: 8081
cache:
  parking-slot:
    prefix: parking-slot
  booking-slot:
    prefix: booking-slot
booking:
  auto-extend:
    threshold-minutes: 15

